<a href="https://colab.research.google.com/github/sreeram222/ML-projects/blob/main/lung_cancer_in_Deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
import pandas as pd
df=pd.read_csv("/content/lung_cancer_examples.csv")
df

           Name      Surname  Age  Smokes  AreaQ  Alkhol  Result
0          John         Wick   35       3      5       4       1
1          John  Constantine   27      20      2       5       1
2        Camela     Anderson   30       0      5       2       0
3          Alex       Telles   28       0      8       1       0
4         Diego     Maradona   68       4      5       6       1
5     Cristiano      Ronaldo   34       0     10       0       0
6        Mihail          Tal   58      15     10       0       0
7         Kathy        Bates   22      12      5       2       0
8        Nicole       Kidman   45       2      6       0       0
9           Ray      Milland   52      18      4       5       1
10      Fredric        March   33       4      8       0       0
11          Yul      Brynner   18      10      6       3       0
12         Joan     Crawford   25       2      5       1       0
13         Jane        Wyman   28      20      2       8       1
14         Anna      Magnani   34      25      4       8       1
15   Katharine       Hepburn   39      18      8       1       0
16   Katharine       Hepburn   42      22      3       5       1
17       Barbra    Streisand   19      12      8       0       0
18      Maggie         Smith   62       5      4       3       1
19      Glenda       Jackson   73      10      7       6       1
20        Jane         Fonda   55      15      1       3       1
21  Maximilian        Schell   33       8      8       1       0
22     Gregory          Peck   22      20      6       2       0
23      Sidney       Poitier   44       5      8       1       0
24         Rex      Harrison   77       3      2       6       1
25         Lee        Marvin   21      20      5       3       0
26        Paul      Scofield   37      15      6       2       0
27         Rod       Steiger   34      12      8       0       0
28        John         Wayne   55      20      1       4       1
29        Gene       Hackman   40      20      2       7       1
30      Marlon        Brando   36      13      5       2       0
31        Jack        Lemmon   56      20      3       3       1
32        Jack     Nicholson   47      15      1       8       1
33       Peter        Finch    62      25      3       4       1
34     Richard      Dreyfuss   26      10      7       2       0
35      Dustin       Hoffman   25      20      8       2       0
36       Henry        Henry    59      20      3       4       1
37      Robert        Duvall   62      15      5       5       1
38       Ellen       Burstyn   33      25      8       2       0
39        Faye       Dunaway   37      10      5       3       0
40       Diane        Keaton   50      20      2       4       1
41        Jane         Fonda   47      12      8       0       0
42       Sally         Field   69      20      5       4       1
43       Sissy        Spacek   63      20      4       5       1
44     Jessica         Lange   39      15      7       2       0
45     Gwyneth       Paltrow   21      20      8       3       0
46       Halle         Berry   31      20      9       4       0
47      Nicole        Kidman   28      10      4       1       0
48    Charlize        Theron   53      20      6       3       1
49   Katharine       Hepburn   62      20      5       6       1
50   Katharine       Hepburn   42      12      6       2       0
51      Barbra     Streisand   44      30      1       6       1
52      Maggie         Smith   26      34      1       8       1
53      Glenda       Jackson   35      20      5       1       0
54      Ernest      Borgnine   26      13      6       1       0
55        Alec      Guinness   77      20      5       4       1
56    Charlton        Heston   75      15      3       5       1
57     Gregory          Peck   43      30      3       8       1
58      Sidney       Poitier   51      25      9       0       0

In [52]:
df.drop(["Name","Surname"],axis=1,inplace=True)
df

    Age  Smokes  AreaQ  Alkhol  Result
0    35       3      5       4       1
1    27      20      2       5       1
2    30       0      5       2       0
3    28       0      8       1       0
4    68       4      5       6       1
5    34       0     10       0       0
6    58      15     10       0       0
7    22      12      5       2       0
8    45       2      6       0       0
9    52      18      4       5       1
10   33       4      8       0       0
11   18      10      6       3       0
12   25       2      5       1       0
13   28      20      2       8       1
14   34      25      4       8       1
15   39      18      8       1       0
16   42      22      3       5       1
17   19      12      8       0       0
18   62       5      4       3       1
19   73      10      7       6       1
20   55      15      1       3       1
21   33       8      8       1       0
22   22      20      6       2       0
23   44       5      8       1       0
24   77       3      2       6       1
25   21      20      5       3       0
26   37      15      6       2       0
27   34      12      8       0       0
28   55      20      1       4       1
29   40      20      2       7       1
30   36      13      5       2       0
31   56      20      3       3       1
32   47      15      1       8       1
33   62      25      3       4       1
34   26      10      7       2       0
35   25      20      8       2       0
36   59      20      3       4       1
37   62      15      5       5       1
38   33      25      8       2       0
39   37      10      5       3       0
40   50      20      2       4       1
41   47      12      8       0       0
42   69      20      5       4       1
43   63      20      4       5       1
44   39      15      7       2       0
45   21      20      8       3       0
46   31      20      9       4       0
47   28      10      4       1       0
48   53      20      6       3       1
49   62      20      5       6       1
50   42      12      6       2       0
51   44      30      1       6       1
52   26      34      1       8       1
53   35      20      5       1       0
54   26      13      6       1       0
55   77      20      5       4       1
56   75      15      3       5       1
57   43      30      3       8       1
58   51      25      9       0       0

In [53]:
df.isna().sum()

Age       0
Smokes    0
AreaQ     0
Alkhol    0
Result    0
dtype: int64

In [54]:
x=df.iloc[:,:-1]
x

    Age  Smokes  AreaQ  Alkhol
0    35       3      5       4
1    27      20      2       5
2    30       0      5       2
3    28       0      8       1
4    68       4      5       6
5    34       0     10       0
6    58      15     10       0
7    22      12      5       2
8    45       2      6       0
9    52      18      4       5
10   33       4      8       0
11   18      10      6       3
12   25       2      5       1
13   28      20      2       8
14   34      25      4       8
15   39      18      8       1
16   42      22      3       5
17   19      12      8       0
18   62       5      4       3
19   73      10      7       6
20   55      15      1       3
21   33       8      8       1
22   22      20      6       2
23   44       5      8       1
24   77       3      2       6
25   21      20      5       3
26   37      15      6       2
27   34      12      8       0
28   55      20      1       4
29   40      20      2       7
30   36      13      5       2
31   56      20      3       3
32   47      15      1       8
33   62      25      3       4
34   26      10      7       2
35   25      20      8       2
36   59      20      3       4
37   62      15      5       5
38   33      25      8       2
39   37      10      5       3
40   50      20      2       4
41   47      12      8       0
42   69      20      5       4
43   63      20      4       5
44   39      15      7       2
45   21      20      8       3
46   31      20      9       4
47   28      10      4       1
48   53      20      6       3
49   62      20      5       6
50   42      12      6       2
51   44      30      1       6
52   26      34      1       8
53   35      20      5       1
54   26      13      6       1
55   77      20      5       4
56   75      15      3       5
57   43      30      3       8
58   51      25      9       0

In [55]:
y=df.iloc[:,-1]
y

0     1
1     1
2     0
3     0
4     1
5     0
6     0
7     0
8     0
9     1
10    0
11    0
12    0
13    1
14    1
15    0
16    1
17    0
18    1
19    1
20    1
21    0
22    0
23    0
24    1
25    0
26    0
27    0
28    1
29    1
30    0
31    1
32    1
33    1
34    0
35    0
36    1
37    1
38    0
39    0
40    1
41    0
42    1
43    1
44    0
45    0
46    0
47    0
48    1
49    1
50    0
51    1
52    1
53    0
54    0
55    1
56    1
57    1
58    0
Name: Result, dtype: int64

In [56]:
from sklearn.preprocessing import MinMaxScaler
mm=MinMaxScaler()
x=mm.fit_transform(x)
x

array([[0.28813559, 0.08823529, 0.44444444, 0.5       ],
       [0.15254237, 0.58823529, 0.11111111, 0.625     ],
       [0.20338983, 0.        , 0.44444444, 0.25      ],
       [0.16949153, 0.        , 0.77777778, 0.125     ],
       [0.84745763, 0.11764706, 0.44444444, 0.75      ],
       [0.27118644, 0.        , 1.        , 0.        ],
       [0.6779661 , 0.44117647, 1.        , 0.        ],
       [0.06779661, 0.35294118, 0.44444444, 0.25      ],
       [0.45762712, 0.05882353, 0.55555556, 0.        ],
       [0.57627119, 0.52941176, 0.33333333, 0.625     ],
       [0.25423729, 0.11764706, 0.77777778, 0.        ],
       [0.        , 0.29411765, 0.55555556, 0.375     ],
       [0.11864407, 0.05882353, 0.44444444, 0.125     ],
       [0.16949153, 0.58823529, 0.11111111, 1.        ],
       [0.27118644, 0.73529412, 0.33333333, 1.        ],
       [0.3559322 , 0.52941176, 0.77777778, 0.125     ],
       [0.40677966, 0.64705882, 0.22222222, 0.625     ],
       [0.01694915, 0.35294118, 0.77777778, 0.        ],
       [0.74576271, 0.14705882, 0.33333333, 0.375     ],
       [0.93220339, 0.29411765, 0.66666667, 0.75      ],
       [0.62711864, 0.44117647, 0.        , 0.375     ],
       [0.25423729, 0.23529412, 0.77777778, 0.125     ],
       [0.06779661, 0.58823529, 0.55555556, 0.25      ],
       [0.44067797, 0.14705882, 0.77777778, 0.125     ],
       [1.        , 0.08823529, 0.11111111, 0.75      ],
       [0.05084746, 0.58823529, 0.44444444, 0.375     ],
       [0.3220339 , 0.44117647, 0.55555556, 0.25      ],
       [0.27118644, 0.35294118, 0.77777778, 0.        ],
       [0.62711864, 0.58823529, 0.        , 0.5       ],
       [0.37288136, 0.58823529, 0.11111111, 0.875     ],
       [0.30508475, 0.38235294, 0.44444444, 0.25      ],
       [0.6440678 , 0.58823529, 0.22222222, 0.375     ],
       [0.49152542, 0.44117647, 0.        , 1.        ],
       [0.74576271, 0.73529412, 0.22222222, 0.5       ],
       [0.13559322, 0.29411765, 0.66666667, 0.25      ],
       [0.11864407, 0.58823529, 0.77777778, 0.25      ],
       [0.69491525, 0.58823529, 0.22222222, 0.5       ],
       [0.74576271, 0.44117647, 0.44444444, 0.625     ],
       [0.25423729, 0.73529412, 0.77777778, 0.25      ],
       [0.3220339 , 0.29411765, 0.44444444, 0.375     ],
       [0.54237288, 0.58823529, 0.11111111, 0.5       ],
       [0.49152542, 0.35294118, 0.77777778, 0.        ],
       [0.86440678, 0.58823529, 0.44444444, 0.5       ],
       [0.76271186, 0.58823529, 0.33333333, 0.625     ],
       [0.3559322 , 0.44117647, 0.66666667, 0.25      ],
       [0.05084746, 0.58823529, 0.77777778, 0.375     ],
       [0.22033898, 0.58823529, 0.88888889, 0.5       ],
       [0.16949153, 0.29411765, 0.33333333, 0.125     ],
       [0.59322034, 0.58823529, 0.55555556, 0.375     ],
       [0.74576271, 0.58823529, 0.44444444, 0.75      ],
       [0.40677966, 0.35294118, 0.55555556, 0.25      ],
       [0.44067797, 0.88235294, 0.        , 0.75      ],
       [0.13559322, 1.        , 0.        , 1.        ],
       [0.28813559, 0.58823529, 0.44444444, 0.125     ],
       [0.13559322, 0.38235294, 0.55555556, 0.125     ],
       [1.        , 0.58823529, 0.44444444, 0.5       ],
       [0.96610169, 0.44117647, 0.22222222, 0.625     ],
       [0.42372881, 0.88235294, 0.22222222, 1.        ],
       [0.55932203, 0.73529412, 0.88888889, 0.        ]])

In [57]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [58]:
from tensorflow import keras
from keras.models import Sequential
ann=Sequential([keras.layers.Dense(6,activation="relu"),
                keras.layers.Dense(7,activation="relu"),
                keras.layers.Dense(1,activation="sigmoid")])

In [59]:
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [60]:
ann.fit(x_train,y_train,batch_size=10,epochs=100)

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 0.4894 - loss: 0.6812
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4478 - loss: 0.6768
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4616 - loss: 0.6716
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4602 - loss: 0.6627
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5005 - loss: 0.6583
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5185 - loss: 0.6535
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4908 - loss: 0.6538
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.4283 - loss: 0.6527
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5074 - loss: 0.6392
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4324 - loss: 0.6483
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4685 - loss: 0.6319
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4324 - loss: 0.6412
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5145 - loss: 0.6264
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5369 - loss: 0.6139
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5801 - loss: 0.6123
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6290 - loss: 0.6080
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5609 - loss: 0.6117
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6321 - loss: 0.6073
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6197 - loss: 0.6057
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6520 - loss: 0.6034
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7467 - loss: 0.5883
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7356 - loss: 0.5881
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7356 - loss: 0.5886
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6800 - loss: 0.5867
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8525 - loss: 0.5498
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7775 - loss: 0.5429
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7916 - loss: 0.5724
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8376 - loss: 0.5582
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8573 - loss: 0.5608
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8045 - loss: 0.5508
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8573 - loss: 0.5454
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8630 - loss: 0.5306
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8561 - loss: 0.5460
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9172 - loss: 0.5120
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8130 - loss: 0.5125
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9074 - loss: 0.4878
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8991 - loss: 0.4878
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9116 - loss: 0.4779
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8882 - loss: 0.5084
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9133 - loss: 0.5024
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9230 - loss: 0.4740
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8827 - loss: 0.4846
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9175 - loss: 0.4588
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9468 - loss: 0.4147
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9704 - loss: 0.4319
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9509 - loss: 0.4393
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9246 - loss: 0.4284
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9761 - loss: 0.4099
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9582 - loss: 0.4242
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9929 - loss: 0.4046
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9929 - loss: 0.3932
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9929 - loss: 0.3823
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9832 - loss: 0.3552
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9582 - loss: 0.3744
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9832 - loss: 0.3615
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9582 - loss: 0.3502
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9582 - loss: 0.3597
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9832 - loss: 0.3385
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9887 - loss: 0.3419
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9749 - loss: 0.3168
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9832 - loss: 0.3252
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9582 - loss: 0.3325
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9582 - loss: 0.2958
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9832 - loss: 0.2885
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9749 - loss: 0.3035
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9887 - loss: 0.2651
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9749 - loss: 0.2713
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9832 - loss: 0.2551
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9582 - loss: 0.2726
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2630
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2602
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2470
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2439
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2224
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2137
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2046
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2088
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.1856
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.1942
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.1989
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.1921
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.1691
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.1775
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.1804
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.1704
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.1566
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.1631
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.1542
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.1420
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.1438
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.1276
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.1391
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.1354
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.1436
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.1207
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.1140
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.1330
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.1270
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.1308
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.1011

In [61]:
y_pred=ann.predict(x_test)
y_pred=(y_pred>0.5)
y_pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step

array([[ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False]])

In [62]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)*100

100.0

In [64]:
ann.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_15 (Dense)                │ (None, 6)              │            30 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 7)              │            49 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 1)              │             8 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 263 (1.03 KB)

 Trainable params: 87 (348.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 176 (708.00 B)

In [65]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[8, 0],
       [0, 4]])

In [74]:
z=ann.predict(mm.transform([[2,3,5,8]]))
print(z)

if z>0.5:
  print("cancer")
else:
  print("cancer free")

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step
[[0.45496997]]
cancer free